import argparse
import copy
import json
import math
import uuid
from pathlib import Path


def get_polygon(obj):
    for key in ("polygon", "outer", "points", "contour"):
        pts = obj.get(key)
        if pts and len(pts) >= 2:
            return pts
    return []


def get_center(obj):
    center = obj.get("center")

    if center and len(center) >= 2:
        return float(center[0]), float(center[1])

    pts = get_polygon(obj)

    if pts:
        xs = [float(p[0]) for p in pts]
        ys = [float(p[1]) for p in pts]

        return sum(xs) / len(xs), sum(ys) / len(ys)

    bbox = obj.get("bbox")

    if bbox and len(bbox) == 4:
        x1, y1, x2, y2 = map(float, bbox)
        return (x1 + x2) / 2.0, (y1 + y2) / 2.0

    raise ValueError("Opening has no center/polygon/bbox")


def get_bbox(obj):
    bbox = obj.get("bbox")

    if bbox and len(bbox) == 4:
        return tuple(map(float, bbox))

    pts = get_polygon(obj)

    if not pts:
        return None

    xs = [float(p[0]) for p in pts]
    ys = [float(p[1]) for p in pts]

    return min(xs), min(ys), max(xs), max(ys)


def get_opening_length_px(obj):
    if obj.get("length") is not None:
        return float(obj["length"])

    bbox = get_bbox(obj)

    if not bbox:
        return 80.0

    x1, y1, x2, y2 = bbox

    return max(
        abs(x2 - x1),
        abs(y2 - y1)
    )


def opening_orientation(obj):
    orientation = obj.get("orientation")

    if orientation in ("horizontal", "vertical"):
        return orientation

    bbox = get_bbox(obj)

    if not bbox:
        return None

    x1, y1, x2, y2 = bbox

    if abs(x2 - x1) >= abs(y2 - y1):
        return "horizontal"

    return "vertical"


def point_to_segment(px, py, ax, ay, bx, by):
    dx = bx - ax
    dy = by - ay

    length2 = dx * dx + dy * dy

    if length2 <= 1e-9:
        return math.hypot(px - ax, py - ay), 0.0, ax, ay

    t = (
        (px - ax) * dx +
        (py - ay) * dy
    ) / length2

    t_clamped = max(0.0, min(1.0, t))

    qx = ax + t_clamped * dx
    qy = ay + t_clamped * dy

    distance = math.hypot(
        px - qx,
        py - qy
    )

    return distance, t_clamped, qx, qy


def find_door_template(template):
    for level in template.get("levels", []):
        for element in level.get("elements", []):
            if element.get("type") == "doorItem":
                return copy.deepcopy(element)

    return None


def build_hole_shape(width_cm, height_cm):
    half_width_m = width_cm / 200.0
    height_m = height_cm / 100.0

    return [
        {
            "x": round(half_width_m, 5),
            "y": round(height_m, 5)
        },
        {
            "x": round(-half_width_m, 5),
            "y": round(height_m, 5)
        },
        {
            "x": round(-half_width_m, 5),
            "y": 0
        },
        {
            "x": round(half_width_m, 5),
            "y": 0
        },
        {
            "x": round(half_width_m, 5),
            "y": round(height_m, 5)
        }
    ]


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "project_json",
        help="JSON generated by build_project_json.py"
    )

    parser.add_argument(
        "classified_json",
        help="JSON containing classified doors/windows"
    )

    parser.add_argument(
        "rooms_json",
        help="rooms JSON used for project generation"
    )

    parser.add_argument(
        "template_json",
        help="original application JSON containing a doorItem"
    )

    parser.add_argument(
        "--output",
        default="output/project_with_doors.json"
    )

    parser.add_argument(
        "--windows-output",
        default="output/window_bindings.json"
    )

    parser.add_argument(
        "--door-height",
        type=float,
        default=202.5
    )

    parser.add_argument(
        "--max-wall-distance",
        type=float,
        default=50.0,
        help="Maximum distance from opening center to segment, cm"
    )

    args = parser.parse_args()

    with open(args.project_json, "r", encoding="utf-8") as f:
        project = json.load(f)

    with open(args.classified_json, "r", encoding="utf-8") as f:
        classified = json.load(f)

    with open(args.rooms_json, "r", encoding="utf-8") as f:
        room_data = json.load(f)

    with open(args.template_json, "r", encoding="utf-8") as f:
        template = json.load(f)

    level = project["levels"][0]

    connectors = {
        c["uuid"]: c
        for c in level["connectors"]
    }

    segments = level["segments"]

    # -------------------------------------------------------
    # Находим границы исходной геометрии в пикселях.
    #
    # build_project_json расширял bbox помещения на половину
    # толщины стены. Повторяем ту же идею.
    # -------------------------------------------------------

    rooms = room_data.get("rooms", [])

    if not rooms:
        raise RuntimeError("No rooms found")

    wall_thickness_cm = float(
        segments[0].get("thickness", 20)
    )

    project_x = [
        float(c["x"])
        for c in connectors.values()
    ]

    project_y = [
        float(c["y"])
        for c in connectors.values()
    ]

    project_min_x = min(project_x)
    project_max_x = max(project_x)

    project_min_y = min(project_y)
    project_max_y = max(project_y)

    # Для текущего проекта исходный scale был приблизительно 1.
    # Получаем реальный масштаб обратно через размеры проекта.
    raw_min_x = float("inf")
    raw_max_x = float("-inf")
    raw_min_y = float("inf")
    raw_max_y = float("-inf")

    room_boxes = []

    for room in rooms:
        bbox = room.get("bbox")

        if bbox and len(bbox) == 4:
            x1, y1, x2, y2 = map(float, bbox)
        else:
            pts = get_polygon(room)

            if not pts:
                continue

            xs = [float(p[0]) for p in pts]
            ys = [float(p[1]) for p in pts]

            x1 = min(xs)
            x2 = max(xs)
            y1 = min(ys)
            y2 = max(ys)

        room_boxes.append(
            (x1, y1, x2, y2)
        )

    if not room_boxes:
        raise RuntimeError("No usable room bounding boxes")

    # Предварительная оценка масштаба.
    room_min_x = min(b[0] for b in room_boxes)
    room_max_x = max(b[2] for b in room_boxes)

    room_min_y = min(b[1] for b in room_boxes)
    room_max_y = max(b[3] for b in room_boxes)

    preliminary_scale_x = (
        (project_max_x - project_min_x) /
        max(room_max_x - room_min_x, 1.0)
    )

    preliminary_scale_y = (
        (project_max_y - project_min_y) /
        max(room_max_y - room_min_y, 1.0)
    )

    preliminary_scale = (
        preliminary_scale_x +
        preliminary_scale_y
    ) / 2.0

    half_wall_px = (
        wall_thickness_cm /
        max(preliminary_scale, 0.0001) /
        2.0
    )

    for x1, y1, x2, y2 in room_boxes:
        raw_min_x = min(
            raw_min_x,
            x1 - half_wall_px
        )

        raw_max_x = max(
            raw_max_x,
            x2 + half_wall_px
        )

        raw_min_y = min(
            raw_min_y,
            y1 - half_wall_px
        )

        raw_max_y = max(
            raw_max_y,
            y2 + half_wall_px
        )

    source_width = raw_max_x - raw_min_x
    source_height = raw_max_y - raw_min_y

    scale_x = (
        (project_max_x - project_min_x) /
        max(source_width, 1.0)
    )

    scale_y = (
        (project_max_y - project_min_y) /
        max(source_height, 1.0)
    )

    print()
    print("Coordinate transform")
    print(
        f"scale_x = {scale_x:.4f} cm/px"
    )
    print(
        f"scale_y = {scale_y:.4f} cm/px"
    )

    def pixel_to_world(px, py):
        wx = (
            project_min_x +
            (px - raw_min_x) * scale_x
        )

        wy = (
            project_min_y +
            (py - raw_min_y) * scale_y
        )

        return wx, wy

    # -------------------------------------------------------
    # Готовим геометрию segments.
    # -------------------------------------------------------

    segment_geometry = []

    for segment in segments:
        a = connectors[
            segment["start"]
        ]

        b = connectors[
            segment["end"]
        ]

        segment_geometry.append({
            "segment": segment,
            "ax": float(a["x"]),
            "ay": float(a["y"]),
            "bx": float(b["x"]),
            "by": float(b["y"]),
        })

    def bind_opening(opening):
        px, py = get_center(opening)

        wx, wy = pixel_to_world(
            px,
            py
        )

        best = None

        for item in segment_geometry:
            distance, t, qx, qy = (
                point_to_segment(
                    wx,
                    wy,
                    item["ax"],
                    item["ay"],
                    item["bx"],
                    item["by"],
                )
            )

            if best is None or distance < best["distance"]:
                best = {
                    "segment": item["segment"],
                    "distance": distance,
                    "t": t,
                    "qx": qx,
                    "qy": qy,
                    "world_x": wx,
                    "world_y": wy,
                }

        if best is None:
            return None

        best["position"] = (
            best["t"] * 100.0
        )

        orientation = opening_orientation(
            opening
        )

        length_px = get_opening_length_px(
            opening
        )

        if orientation == "horizontal":
            width_cm = (
                length_px * scale_x
            )
        elif orientation == "vertical":
            width_cm = (
                length_px * scale_y
            )
        else:
            width_cm = (
                length_px *
                ((scale_x + scale_y) / 2.0)
            )

        best["width_cm"] = width_cm
        best["orientation"] = orientation
        best["pixel_center"] = [px, py]

        return best

    # -------------------------------------------------------
    # DOORS
    # -------------------------------------------------------

    door_template = find_door_template(
        template
    )

    if door_template is None:
        raise RuntimeError(
            "Template JSON contains no doorItem"
        )

    output_elements = []

    door_bindings = []

    doors = classified.get(
        "doors",
        []
    )

    for index, opening in enumerate(doors):
        binding = bind_opening(
            opening
        )

        if binding is None:
            continue

        if (
            binding["distance"] >
            args.max_wall_distance
        ):
            print(
                f"WARNING: door {index + 1} "
                f"is {binding['distance']:.1f} cm "
                f"from nearest segment"
            )

        segment = binding["segment"]

        thickness = float(
            segment.get(
                "thickness",
                wall_thickness_cm
            )
        )

        width_cm = max(
            40.0,
            float(binding["width_cm"]) * 1.12
        )

        door = copy.deepcopy(
            door_template
        )

        door_uuid = str(
            uuid.uuid4()
        )

        door["uuid"] = door_uuid

        door["type"] = "doorItem"

        door["name"] = (
            f"wall_item_door_{index + 1}"
        )

        # Materials in the template reference the original door UUID.
        # Each generated door must point its materials to its own UUID.
        for material in door.get("materials", []):
            material["itemUuid"] = door_uuid

        door["size"] = {
            "x": round(width_cm, 3),
            "y": round(
                args.door_height,
                3
            ),
            "z": round(
                thickness,
                3
            )
        }

        wall = door.setdefault(
            "wall",
            {}
        )

        wall["uuid"] = (
            segment["uuid"]
        )

        wall["position"] = round(
            binding["position"],
            6
        )

        wall["alignment"] = 0.5
        wall["offset"] = 0
        wall["side"] = "left"

        wall["holeShape"] = (
            build_hole_shape(
                width_cm,
                args.door_height
            )
        )

        door["position"] = {
            "z": 0
        }

        door["recess"] = 0
        door["doorOpensOutwards"] = False

        # Сохраняем тип/модель двери из template,
        # но корректируем scale под распознанный размер.
        model = door.get("model")

        if model:
            model_size = model.get(
                "size",
                {}
            )

            mx = float(
                model_size.get("x", width_cm)
                or width_cm
            )

            my = float(
                model_size.get(
                    "y",
                    args.door_height
                )
                or args.door_height
            )

            mz = float(
                model_size.get("z", thickness)
                or thickness
            )

            door["scale"] = {
                "x": width_cm / mx,
                "y": args.door_height / my,
                "z": thickness / mz
            }

        output_elements.append(
            door
        )

        door_bindings.append({
            "door": index + 1,
            "wall_uuid": segment["uuid"],
            "position_percent": round(
                binding["position"],
                3
            ),
            "width_cm": round(
                width_cm,
                2
            ),
            "distance_to_wall_cm": round(
                binding["distance"],
                2
            ),
        })

    # -------------------------------------------------------
    # WINDOWS
    #
    # Пока только точная геометрическая привязка.
    # Структуру windowItem не выдумываем без реального
    # windowItem из вашего приложения.
    # -------------------------------------------------------

    window_bindings = []

    windows = classified.get(
        "windows",
        []
    )

    for index, opening in enumerate(windows):
        binding = bind_opening(
            opening
        )

        if binding is None:
            continue

        segment = binding["segment"]

        window_bindings.append({
            "window": index + 1,

            "pixel_center":
                binding["pixel_center"],

            "world_center": [
                round(
                    binding["world_x"],
                    3
                ),
                round(
                    binding["world_y"],
                    3
                )
            ],

            "wall_uuid":
                segment["uuid"],

            "position_percent":
                round(
                    binding["position"],
                    3
                ),

            "width_cm":
                round(
                    binding["width_cm"],
                    2
                ),

            "distance_to_wall_cm":
                round(
                    binding["distance"],
                    2
                ),

            "orientation":
                binding["orientation"],
        })

    # -------------------------------------------------------
    # В project пока добавляем двери.
    # -------------------------------------------------------

    level["elements"] = (
        output_elements
    )

    output_path = Path(
        args.output
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with output_path.open(
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            project,
            f,
            indent=2,
            ensure_ascii=False
        )

    windows_path = Path(
        args.windows_output
    )

    windows_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with windows_path.open(
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            {
                "windows": window_bindings
            },
            f,
            indent=2,
            ensure_ascii=False
        )

    print()
    print("DONE")
    print()
    print(
        f"Doors detected:      {len(doors)}"
    )
    print(
        f"Doors added:         {len(output_elements)}"
    )
    print(
        f"Windows detected:    {len(windows)}"
    )
    print(
        f"Windows bound:       {len(window_bindings)}"
    )
    print()
    print(
        f"Project:  {output_path}"
    )
    print(
        f"Windows:  {windows_path}"
    )

    print()
    print("Door bindings:")

    for item in door_bindings:
        print(
            f"  Door {item['door']}: "
            f"wall={item['wall_uuid']} "
            f"position={item['position_percent']}% "
            f"width={item['width_cm']}cm "
            f"distance={item['distance_to_wall_cm']}cm"
        )

    print()
    print("Window bindings:")

    for item in window_bindings:
        print(
            f"  Window {item['window']}: "
            f"wall={item['wall_uuid']} "
            f"position={item['position_percent']}% "
            f"width={item['width_cm']}cm "
            f"distance={item['distance_to_wall_cm']}cm"
        )


if __name__ == "__main__":
    main()
